version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"

  cli:
    build: ./cli
    depends_on:
      - api-gateway
    stdin_open: true  # Required for interactive input
    tty: true        # Required for interactive input